---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cam-mongo-pv
  labels:
    type: cam-mongo
spec:
  capacity:
    storage: 15Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteMany
  nfs:
    server: mycluster.icp
    path: /storage/CAM_db
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cam-bpd-appdata-pv
  labels:
    type: cam-bpd-appdata
spec:
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteMany
  nfs:
    server: mycluster.icp
    path: /storage/CAM_bpd
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cam-terraform-pv
  labels:
    type: cam-terraform
spec:
  capacity:
    storage: 15Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    -  ReadWriteMany
  nfs:
    server: mycluster.icp
    path: /storage/CAM_terraform
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cam-logs-pv
  labels:
    type: cam-logs
spec:
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    -  ReadWriteMany
  nfs:
    server: mycluster.icp
    path: /storage/CAM_logs
