apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-prometheus-alertrules
  namespace: kube-system
  labels:
    app: monitoring-prometheus
    chart: ibm-icpmonitoring-1.2.0
    component: prometheus
    heritage: Tiller
    release: monitoring
data:
  alert.rules: |-
    groups:
    - name: a.rules
      rules:
      - alert: NodeMemoryUsage
        expr: ((node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes))/ node_memory_MemTotal_bytes) * 100 > 85
        for: 5m
        annotations:
          DESCRIPTION: '{{ "{{ " }} $labels.instance {{ " }}" }}: Memory usage is above the 85% threshold.  The current value is: {{ "{{ " }} $value {{ " }}" }}.'
          SUMMARY: '{{ "{{ " }}$labels.instance{{ " }}" }}: High memory usage detected'
      - alert: HighCPUUsage
        expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 85
        for: 5m
        annotations:
          description: '{{ "{{ " }} $labels.instance {{ " }}" }}: CPU usage is above the 85% threshold.  The current value is: {{ "{{ " }} $value {{ " }}" }}.'
          summary: High CPU Usage
      - alert: failedJobs
        expr: kube_job_failed != 0
        annotations:
          description: 'Job {{ "{{ " }} $labels.exported_job {{ " }}" }} in namespace {{ "{{ " }} $labels.namespace {{ " }}" }} failed for some reason.'
          summary: Failed job
      - alert: elasticsearchClusterHealth
        expr: elasticsearch_cluster_health_up != 1
        for: 5m
        annotations:
          description: Elasticsearch cluster's health status is not green.
          summary: Elasticsearch cluster not healthy
      - alert: podsTerminated
        expr: sum_over_time(kube_pod_container_status_terminated_reason{reason!="Completed"}[1h]) > 0
        annotations:
          description: 'Pod {{ "{{ " }} $labels.pod {{ " }}" }} in namespace {{ "{{ " }} $labels.namespace {{ " }}" }} has a termination status other than completed.'
          summary: Pod was terminated
      - alert: podsRestarting
        expr: increase(kube_pod_container_status_restarts_total[1h]) > 5
        annotations:
          description: 'Pod {{ "{{ " }} $labels.pod {{ " }}" }} in namespace {{ "{{ " }} $labels.namespace {{ " }}" }} is restarting a lot'
          summary: Pod restarting a lot
