apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-prometheus-alertmanager
  namespace: kube-system
  labels:
    app: monitoring-prometheus
    chart: ibm-icpmonitoring-1.2.0
    component: alertmanager
    heritage: Tiller
    release: monitoring
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 20s
      slack_api_url: 'https://hooks.slack.com/services/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'

    receivers:
      - name: 'slack-notifications'
        slack_configs:
        - channel: '#ibmcloudprivate'
          text: 'Nodes: {{ range .Alerts }}{{ .Labels.instance }} {{ end }}      ---- Summary: {{ .CommonAnnotations.summary }}      ---- Description: {{ .CommonAnnotations.description }}       ---- https://9.30.189.183:8443/prometheus/alerts '
    route:
      receiver: 'slack-notifications'
      group_by: [alertname, datacenter, app]
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1m
