{
  "kind": "Secret",
  "apiVersion": "v1",
  "metadata": {
    "name": "tasecret",
    "namespace": "default",
    "annotations": {}
  },
  "type": "",
  "data": {
    "db_username": "4oCcYWRtaW7igJ0=",
    "secret": "4oCcYWRtaW7igJ0="
  }
}
